appserver:
  name: myapp
  version: 0.0.1
  host: localhost
  port: 8003
  workers: 5
  debug: true

pg:
  host: localhost
  port: 5432
  user: postgres
  db_schema: myapp
  password: "123456"
  database: postgres

redis:
    host: localhost
    port: 6379
    db: 0
    password: ""
    max_connections: 10
    project_prefix: "myapp"
    timeout: 2
    expire_seconds: 60

kafka:
  bootstrap_servers: localhost:9092
  enable: true
  topics:
    chat_task:
      enable: true
      topic_name: chat_task_topic
      group_id: chat_task_group
      num_consumers: 2
    log_task:
      enable: true
      topic_name: log_task_topic
      group_id: log_task_group
      num_consumers: 1

external_api:
  myapp:
    host: localhost
    port: 8003
    prefix: ''
    protocol: http

log:
  level: DEBUG