appserver:
  name: myapp
  version: 0.0.1
  host: localhost
  port: 8003
  workers: 5
  debug: true

pg:
  host: localhost
  port: 5432
  user: postgres
  schema: myapp
  password: "123456"
  database: postgres

redis:
    host: localhost
    port: 6379
    db: 0
    password: ""
    max_connections: 10
    project_prefix: "myapp"
    timeout: 2
    expire_seconds: 60

kafka:
  host: localhost
  port: 9092
  enable: true
  topics:
    dev_a:
      name: dev_a
      num: 1
    dev_b:
      name: dev_b
      num: 1

external_api:
  myapp:
    host: localhost
    port: 8003
    prefix: ''
    protocol: http

log:
  level: DEBUG