appserver:
  name: myapp
  version: 0.0.1
  host: localhost
  port: 8003
  workers: 5

pg:
  host: localhost
  port: 5432
  user: postgres
  schema: myapp
  password: "123456"
  database: postgres

redis:
    host: localhost
    port: 6379
    db: 0
    password: ""
    max_connections: 10
    project_prefix: "test:app"
    timeout: 2
    expire_seconds: 60

external_api:
  myapp:
    host: localhost
    port: 8003
    prefix: ''
    protocol: http

log:
  level: DEBUG